export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const CUSTOMER_VIEW_REQUEST = "CUSTOMER_VIEW_REQUEST";
export const CUSTOMER_VIEW_SUCCESS = "CUSTOMER_VIEW_SUCCESS";
export const CUSTOMER_VIEW_ERROR = "CUSTOMER_VIEW_ERROR";