export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const CUSTOMER_VIEW_REQUEST = "CUSTOMER_VIEW_REQUEST";
export const CUSTOMER_VIEW_SUCCESS = "CUSTOMER_VIEW_SUCCESS";
export const CUSTOMER_VIEW_ERROR = "CUSTOMER_VIEW_ERROR";

export const EMPLOYEE_VIEW_REQUEST = "EMPLOYEE_VIEW_REQUEST";
export const EMPLOYEE_VIEW_SUCCESS = "EMPLOYEE_VIEW_SUCCESS";
export const EMPLOYEE_VIEW_ERROR = "EMPLOYEE_VIEW_ERROR";

export const MOVIE_VIEW_REQUEST = "MOVIE_VIEW_REQUEST";
export const MOVIE_VIEW_SUCCESS = "MOVIE_VIEW_SUCCESS";
export const MOVIE_VIEW_ERROR = "MOVIE_VIEW_ERROR";

export const PAY_VIEW_REQUEST = "PAY_VIEW_REQUEST";
export const PAY_VIEW_SUCCESS = "PAY_VIEW_SUCCESS";
export const PAY_VIEW_ERROR = "PAY_VIEW_ERROR";

export const THEATER_GET_REQUEST = "THEATER_GET_REQUEST";
export const THEATER_GET_SUCCESS = "THEATER_GET_SUCCESS";
export const THEATER_GET_ERROR = "THEATER_GET_ERROR";

export const BRANCH_GET_REQUEST = "BRANCH_GET_REQUEST";
export const BRANCH_GET_SUCCESS = "BRANCH_GET_SUCCESS";
export const BRANCH_GET_ERROR = "BRANCH_GET_ERROR";

export const BRANCH_POST_REQUEST = "BRANCH_POST_REQUEST";
export const BRANCH_POST_SUCCESS = "BRANCH_POST_SUCCESS";
export const BRANCH_POST_ERROR = "BRANCH_POST_ERROR";

export const MOVIE_GET_REQUEST = "MOVIE_GET_REQUEST";
export const MOVIE_GET_SUCCESS = "MOVIE_GET_SUCCESS";
export const MOVIE_GET_ERROR = "MOVIE_GET_ERROR";

export const SEAT_GET_REQUEST = "SEAT_GET_REQUEST";
export const SEAT_GET_SUCCESS = "SEAT_GET_SUCCESS";
export const SEAT_GET_ERROR = "SEAT_GET_ERROR";

export const SEAT_POST_REQUEST = "SEAT_POST_REQUEST";
export const SEAT_POST_SUCCESS = "SEAT_POST_SUCCESS";
export const SEAT_POST_ERROR = "SEAT_POST_ERROR";

export const BOOKING_POST_REQUEST = "BOOKING_POST_REQUEST";
export const BOOKING_POST_SUCCESS = "BOOKING_POST_SUCCESS";
export const BOOKING_POST_ERROR = "BOOKING_POST_ERROR";

export const BOOKING_EDIT_REQUEST = "BOOKING_EDIT_REQUEST";
export const BOOKING_EDIT_SUCCESS = "BOOKING_EDIT_SUCCESS";
export const BOOKING_EDIT_ERROR = "BOOKING_EDIT_ERROR";

export const PAYMENT_POST_REQUEST = "PAYMENT_POST_REQUEST";
export const PAYMENT_POST_SUCCESS = "PAYMENT_POST_SUCCESS";
export const PAYMENT_POST_ERROR = "PAYMENT_POST_ERROR";

export const SHOW_GET_REQUEST = "SHOW_GET_REQUEST";
export const SHOW_GET_SUCCESS = "SHOW_GET_SUCCESS";
export const SHOW_GET_ERROR = "SHOW_GET_ERROR";

export const LANGUAGE_GET_REQUEST = "LANGUAGE_GET_REQUEST";
export const LANGUAGE_GET_SUCCESS = "LANGUAGE_GET_SUCCESS";
export const LANGUAGE_GET_ERROR = "LANGUAGE_GET_ERROR";

export const MOVIE_POST_REQUEST = "MOVIE_POST_REQUEST";
export const MOVIE_POST_SUCCESS = "MOVIE_POST_SUCCESS";
export const MOVIE_POST_ERROR = "MOVIE_POST_ERROR";

export const MOVIE_EDIT_REQUEST = "MOVIE_EDIT_REQUEST";
export const MOVIE_EDIT_SUCCESS = "MOVIE_EDIT_SUCCESS";
export const MOVIE_EDIT_ERROR = "MOVIE_EDIT_ERROR";

export const MOVIE_DELETE_REQUEST = "MOVIE_DELETE_REQUEST";
export const MOVIE_DELETE_SUCCESS = "MOVIE_DELETE_SUCCESS";
export const MOVIE_DELETE_ERROR = "MOVIE_DELETE_ERROR";

export const CUSTOMER_POST_REQUEST = "CUSTOMER_POST_REQUEST";
export const CUSTOMER_POST_SUCCESS = "CUSTOMER_POST_SUCCESS ";
export const CUSTOMER_POST_ERROR = "CUSTOMER_POST_ERROR";

export const CUSTOMER_EDIT_REQUEST = "CUSTOMER_EDIT_REQUEST";
export const CUSTOMER_EDIT_SUCCESS = "CUSTOMER_EDIT_SUCCESS ";
export const CUSTOMER_EDIT_ERROR = "CUSTOMER_EDIT_ERROR";

export const DASHBORD_IMAGE_REQUEST = "DASHBORD_IMAGE_REQUEST";
export const DASHBORD_IMAGE_SUCCESS = "DASHBORD_IMAGE_SUCCESS ";
export const DASHBORD_IMAGE_ERROR = "DASHBORD_IMAGE_ERROR";